"$schema" = 'https://starship.rs/config-schema.json'

# $direnv$directory$git_status${custom.git_status}${custom.git_staged}$package$git_commit$git_state $fill $cmd_duration
format = """
$direnv$directory${custom.jj}$git_status$package$git_commit$git_state $fill $cmd_duration
$jobs$character
"""

[character]
success_symbol = '[→](green)'
error_symbol = '[✗](red)'

[git_status]
format = '$ahead_behind$conflicted'
ahead = '[↑](blue) '
behind = '[↓](red) '
diverged = '[↓](red) [↑](blue) '
conflicted = '[!](red) '

[custom.git_status]
when = 'git rev-parse --is-inside-work-tree >/dev/null 2>&1 && ! git diff --quiet --exit-code || [ -n "$(git ls-files --exclude-standard --others)" ]'
symbol = '* '
style = 'yellow'

[custom.git_staged]
when = 'git rev-parse --is-inside-work-tree && ! git diff --cached --quiet --exit-code'
symbol = '✓ '
style = 'blue'

[custom.jj]
command = '''
jj log --ignore-working-copy --no-graph --color always -r @ -T "separate(
  ' ',
  if(empty, '[empty]'),
  if(conflict, label('conflict', 'conflict')),
  description.first_line(),
)"
'''
when = 'jj root --quiet'

[git_commit]
format = '[($tag )](green)'
commit_hash_length = 7
only_detached = false
tag_disabled = false
tag_symbol = ''

[git_state]
format = '$state([$progress_current:$progress_total](yellow)) '
rebase = "[rebasing](cyan)"
merge = "[merging](yellow)"
cherry_pick = "[cherry picking](red)"
bisect = "[bisecting](red)"

[git_branch]
format = '[$branch](purple) '
only_attached = true

[package]
format = '[$version](blue) '

[jobs]
format = '[$symbol](red) '
symbol = '▸'
number_threshold = 2

[directory]
format = '[$path]($style) '
style = 'yellow'
truncate_to_repo = false
truncation_length = 1

[direnv]
format = '[$allowed]($style)'
style = 'yellow'
allowed_msg = '*'
not_allowed_msg = ''
disabled = false
detect_files = ['.env']

[cmd_duration]
show_milliseconds = true
min_time = 100
format = '[$duration](bright-black)'

[fill]
symbol = ' '
style = 'bold green'
