format = """
$directory$package$git_state$git_branch$git_commit$cmd_duration
$jobs$git_status$character
"""

[character]
  success_symbol = '[➜](bold green)'
  error_symbol = '[✗](bold red)'

[git_status]
  format = '([$stashed](bold cyan))([$modified](bold yellow))([$untracked](bold green))([$deleted](bold red))([$staged](bold cyan))([$conflicted](bold red))'
  conflicted = '▸◂ '
  ahead	= '↑ '
  behind = '↓'
  diverged = '◂▸ '
  up_to_date = '✔︎ '
  stashed	= '⚬ '
  modified = '* '
  untracked	= '+ '
  deleted	= '− '
  staged = '• '

[git_commit]
  format = '[$hash](bright-green)(:[$tag](bright-purple)) '
  commit_hash_length = 7
  only_detached = false
  tag_disabled = false
  tag_symbol = ''


[git_state]
  format = '$state( [$progress_current:$progress_total](bold yellow)) '
  rebase = "[rebasing](bold cyan)"
  merge = "[merging](bold yellow)"
  cherry_pick = "[pick](bold red)"

[git_branch]
  format = '[$branch](bold bright-purple):'
  only_attached = true

[package]
  format = '[$version](bold blue) '

[jobs]
  format ='[$symbol$number](bold red) '
  symbol = '▸'
  number_threshold = 2

[directory]
  format = '[$path]($style)[$read_only]($read_only_style) '
  style = 'bold bright-yellow'
  truncate_to_repo = false

[battery]
  full_symbol = ''
  charging_symbol = ''
  discharging_symbol = ''
  empty_symbol = ''
