"$schema" = 'https://starship.rs/config-schema.json'

format = """
$directory$package$git_commit$git_branch$git_state$cmd_duration
$jobs$git_status$character
"""

[character]
success_symbol = '[→](green)'
error_symbol = '[✗](red)'

[git_status]
format = '$stashed$ahead_behind$untracked$deleted$modified$staged$conflicted'
conflicted = '[▸◂](red) '
ahead = '[↑ $count](blue) '
behind = '[↓ $count](red) '
diverged = '[↓ $behind_count](red) [↑ $ahead_count](blue) '
up_to_date = ''
stashed = '[···](red) '
modified = '[*](yellow) '
untracked = '[+](green) '
renamed = '[=](cyan) '
deleted = '[−](red) '
staged = '[•](blue) '

[git_commit]
format = '[($tag )](green)'
commit_hash_length = 7
only_detached = false
tag_disabled = false
tag_symbol = ''

[git_state]
format = '$state([$progress_current:$progress_total](yellow)) '
rebase = "[rebasing](cyan)"
merge = "[merging](yellow)"
cherry_pick = "[cherry-picking](red)"
bisect = "[bisecting](red)"

[git_branch]
format = '[$branch](purple) '
only_attached = true

[package]
format = '[$version](blue) '

[jobs]
format = '[$symbol$number](bold red) '
symbol = '▸'
number_threshold = 2

[directory]
format = '[$path]($style) '
style = 'yellow'
truncate_to_repo = false
truncation_length = 2
