format = """
$directory$git_state$git_branch$git_commit$cmd_duration
$jobs$git_status$character
"""

[character]
  success_symbol = '[➜](bold green)'
  error_symbol = '[✗](bold red)'

[git_status]
  format = '$ahead_behind$stashed$untracked$deleted$modified$staged$conflicted'
  conflicted = '[▸◂](bold red) '
  ahead	= '[↑ $count](bold blue) '
  behind = '[↓ $count](bold red) '
  diverged = '[↓ $behind_count](bold red) [↑ $ahead_count](bold blue) '
  up_to_date = ''
  stashed	= '[•](bold red) '
  modified = '[*](bold yellow) '
  untracked	= '[+](bold green) '
  renamed = '[=](bold cyan) '
  deleted	= '[−](bold red) '
  staged = '[•](bold blue) '

[git_commit]
  format = '[$hash](bright-green) '
  commit_hash_length = 7
  only_detached = false
  tag_disabled = false
  tag_symbol = ''


[git_state]
  format = '$state( [$progress_current:$progress_total](bold yellow)) '
  rebase = "[rebasing](bold cyan)"
  merge = "[merging](bold yellow)"
  cherry_pick = "[pick](bold red)"

[git_branch]
  format = '[$branch](bold bright-purple):'
  only_attached = true

[package]
  format = '[$version](bold blue) '

[jobs]
  format ='[$symbol$number](bold red) '
  symbol = '▸'
  number_threshold = 2

[directory]
  format = '[$path]($style)[$read_only]($read_only_style) '
  style = 'bold bright-yellow'
  truncate_to_repo = false

[battery]
  full_symbol = ''
  charging_symbol = ''
  discharging_symbol = ''
  empty_symbol = ''
