[bindings]
root.move_up = ["p"]
root.move_down = ["n"]
root.move_up_line = ["<up>"]
root.move_down_line = ["<down>"]
root.move_prev_section = ["<left>"]
root.move_next_section = ["<right>"]
root.move_parent_section = []
root.half_page_up = []
root.half_page_down = []
